name: CI_backend

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run pytest
      run: poetry run pytest

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t sentiment-analyzer .

    - name: Run container and check health
      run: |
        docker run -d -p 8000:80 --name test-app sentiment-analyzer
        sleep 5
        curl --fail http://localhost:8000/sentiment?input=I+like+icecream || (docker logs test-app && exit 1)

    - name: Tag and push Docker image with commit SHA
      if: github.ref == 'refs/heads/main'
      run: |
        SHORT_SHA=${GITHUB_SHA::7}
        docker tag sentiment-analyzer martinezmatias/sentiment-analyzer:$SHORT_SHA
        docker push martinezmatias/sentiment-analyzer:$SHORT_SHA

        docker tag sentiment-analyzer martinezmatias/sentiment-analyzer:latest
        docker push martinezmatias/sentiment-analyzer:latest